### ISSUE TITLE
send nul on serial fails silently

### ISSUE THREAD

**Issue by wimp1** [PinguinoIDE/pinguino-libraries#3]
On X3 + Pinguino-Micro.. Printing nul character results in nothing.

char b;
b=0;
Serial2.printf("%c",b); // nothing
b=10;
Serial2.printf("%c",b); // works

**Comment by rblanchot** [comment]
%c prints ASCII code
ASCII code 0   = Null or "End of String", so nothing is printed
ASCII code 10 = Line Feed
I see no error there.
It compiles perfectly under Pinguino IDE v11.
