### ISSUE TITLE
Interrupts Compiling

### ISSUE THREAD

**Issue by VOskar** [PinguinoIDE/pinguino-libraries#8]
File /examples/08.Interrupt/P32-Interrupt-Timer1.pde cannot be compiled on all 32bit PICs

**Comment by rblanchot** [comment]
The issue doesn't come from the libraries but from the IDE preprocessor.
I assign it to Yeison.

**Comment by rblanchot** [comment]
All fixed.
I've published new examples how to use interrupt with PIC32MX.
IRQ have predefined names so if you want to use the Timer1 interrupt you must use Timer1Interrupt() function. Nothing else. No more tricky declaration.
