### ISSUE TITLE
I2C1 and I2C2

### ISSUE THREAD

**Issue by VOskar** [PinguinoIDE/pinguino-libraries#9]
When I use commands from file I2C1, I2C2, PI2C1 or PI2C2 .pdl32 (the same commands), it use commands from file PI2C1 or PI2C2 .pdl32, but files pinguinoi2c1.c and pinguinoi2c2.c aren't exist. Please fix it. Thank You.

**Comment by rblanchot** [comment]
Fixed in the libraries.
However there is still a preprocessor issue (already reported here : https://github.com/PinguinoIDE/pinguino-libraries/issues/8)

**Comment by rblanchot** [comment]
All fixed.
